name: Release build & push to Docker Hub

on:
  push: 
    branches:
      - main

jobs:
  release-build-push:
    uses: ./.github/workflows/build-and-push-docker-image.yaml
    with:
      imageName: eventhub-api
      imageTag: latest
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}